config/routes.rb
Rails.application.routes.draw do

# 管理者側
  #scope module: :admin do
    devise_for :admins
  #
  # , controllers: {
  #   sessions:      'admin/sessions',
  #   passwords:     'admin/passwords',
  #   registrations: 'admin/registrations'
  # }
  # root 'admin/sessions#top'
  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :order_items, only: [:update]
    get '/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end


# 顧客側
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  root 'customer/items#top'
  get '/about' => 'customer/items#about', as: 'about'

  scope module: :customer do
    scope 'customers' do

      resources :items, only: [:index, :show]
      resources :orders, only: [:new,  :create,  :index, :show] do
       collection do
          get 'log'
          get 'thanks'
        end
      end
      resource :customers, only: [:show, :edit, :update, :quit, :out] do
        collection do
          get 'quit'
          patch 'out'
       end
     end
     resources :carts, only: [:index, :create, :update, :destroy] do
       collection do
         delete 'all_destroy'
       end
     end
     resources :addresses, only: [:index, :create, :edit, :update, :destroy]
   end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          # sessionsコントローラーで使用する定義
  has_many :carts
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  has_many :addresses, dependent: :destroy
  has_many :orders

  def total_price
    sum = 0
    self.carts.each do |cart_item|
     sum += cart_item.quantity * cart_item.item.non_taxed_price
    end
    return sum
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order_items

  enum payment: {"クレジットカード": 0, "銀行振込": 1}
  enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

  def sub_price
    sum = 0
    self.order_items.each do |order_item|
      sum += order_item.purchase_price*order_item.quantity
    end
    return sum
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  def quit
  end

  def out
  end
  
  private

  def customer_params
    params.require(:customer).permit(:family_name, :family_name_kana, :first_name, :first_name_kana, :phone_number, :zipcode, :address, :email, :is_deleted)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:id]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
       redirect_to admin_order_path(@order.id)
    else
       render 'show'
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

before_action :authenticate_customer!

  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.address
      if @address.save
        redirect_to addresses_path
      else
        @addresses = current_customer.address
        render 'index'
      end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
      if @address.update(address_params)
        redirect_to addresses_path
      else
        render "edit"
      end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    @addresses = current_customer.address
      redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:zipcode, :address, :name)

  end
end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController
  def index
    @carts = current_customer.carts
    @total_price = 0
		@carts.each do |cart|
			@total_price += cart.item.non_taxed_price * cart.quantity
		end
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.customer_id = current_customer.id
    # @carts = current_customer.carts
    @already = current_customer.carts.find_by(item_id: @cart.item_id)
    if @already.present?
      new_quantity = @already.quantity + @cart.quantity
      @already.update_attribute(:quantity, new_quantity)
    else
      @cart.save
    end
    redirect_to carts_path
  end

  def update
    @cart = Cart.find(params[:id])
    if @cart.update(cart_params)
      redirect_to carts_path
    else render 'index'
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    if @cart.destroy
      redirect_to carts_path
    else render 'index'
    end
  end

  def all_destroy
    Cart.destroy_all
    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:item_id, :quantity)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  def quit
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    # ログアウトしてトップページに飛ぶ
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:family_name, :family_name_kana, :first_name, :first_name_kana, :phone_number, :zipcode, :address)
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  MAX_DISPLAY_RELATED_PRODUCTS = 4

  def top
    @genres = Genre.where(directed_graph: true)
    # @items =Item.limit(8).offset(4)
    @items = Item.where(on_sale: true)
  end

  def about
  end

  def index
    @genres = Genre.where(directed_graph: true)
    @items = Item.where(on_sale: true).page(params[:page]).per(4)

  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(directed_graph: true)
    @cart = Cart.new
  end

  private
  def items_params
    params.require(:item).permit(:explanation, :non_taxed_price, :image, :on_sale, :genre_id)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @order = Order.new
    @address = Address.where(customer: current_customer)
  end

  def log
    @carts = Cart.all
		@order = Order.new

	  if params[:address_option] == "address"
      #ご自身の住所
      @order.zipcode = current_customer.zipcode
      @order.address = current_customer.address
      @order.name = current_customer.family_name + current_customer.first_name

    elsif params[:address_option] == "addresses"
      if params[:addresses].blank?
        render :new
        return
      end
        #登録済住所から選択
        @order.zipcode = Address.find(params[:addresses]).zipcode
        @order.address = Address.find(params[:addresses]).address
        @order.name = Address.find(params[:addresses]).name
      else params[:address_option] == "new_address"
        @order.zipcode = params[:zipcode]
        @order.address = params[:address]
        @order.name = params[:name]
    end

    @order.payment = params[:payment_method]
    @order.shipfee = 800

  end

  def create
    @order = Order.new(order_params)
    @order.total_price = current_customer.total_price * 1.10 + @order.shipfee
    @order.customer_id = current_customer.id
    @order.save!
    # もし情報入力でnew_addressの場合Addressに保存
    if params[:address_option] == "new_address"
      current_customer.addresses.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @carts = current_customer.carts
    @carts.each do |cart|
    # OrderItem.create(purchase_price: cart.item.non_taxed_price, order_id: @order.id, item_id: cart.item.id, quantity: cart.quantity)
    @order_item = OrderItem.new
    @order_item.purchase_price = cart.item.non_taxed_price
    @order_item.order_id = @order.id
    @order_item.item_id  = cart.item.id
    @order_item.quantity = cart.quantity
    @order_item.save
    end

    # 注文完了後、カート商品を空にする
  # @carts.destroy_all
    if @order.save
      @carts = current_customer.carts
      @carts.destroy_all
      redirect_to thanks_orders_path
    else
      @order.customer_id = current_customer.id
      @customer = current_customer
      render :new
    end
  end

  def thanks
  end

  def index
      @orders = Order.all
      #Order.where(customer_id: current_customer.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_status = @order.order_status
  end

  private
    def address_params
      params.require(:order).permit(:zipcode, :address, :name)
    end

    def order_params
      params.require(:order).permit( :name, :zipcode, :address, :payment, :shipfee, :order_status)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def after_sign_in_path_for(resource)
   customers_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :email, :zipcode, :address, :phone_number ])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]

  # # GET /resource/sign_in
  # # def new
  # #   super
  # # end

  # # POST /resource/sign_in
  # # def create
  # #   super
  # # end

  # # DELETE /resource/sign_out
  # # def destroy
  # #   super
  # # end

 protected
 # 退会済のユーザーを弾く
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end

  def quit
  end

  def out
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def log
  end

  def create
  end

  def thanks
  end

  def index
  end

  def show
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def tax_price(a)
    a * 1.1
  end

  # def sub_price(b)
  #   b.order_item.non_taxed_price * b.quantity
  # end
end

app/views/customer/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/customer/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="title">
	          <h2>注文履歴一覧</h2>
	        </div>
			<% if @orders.present? %>

			<div class="orders-table">
				<table class="table">
					<thead>
						<tr class="active">
							<th>注文日</th>
							<th>配送先</th>
							<th>注文商品</th>
							<th>支払金額</th>
							<th>ステータス</th>
							<th>注文詳細</th>
						</tr>
					</thead>
					<tbody class="order-items">
					  <tr>
						 <% @orders.each do |order| %>
						 	<td><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>

			                <td class="text-left">
		    		          <%= order.zipcode %><br>
		    		          <%= order.address %><br>
		    		          <%= order.name %>
		    		        </td>
			               <td>
			                <% order.order_items.each do |order_item| %>
	    		          	<%= order_item.item.name %><br>
		    		         <% end %>
		    		        </td>
		    		        <td class="text-right">
		    		          <%= order.total_price.floor.to_s(:delimited) %>円
		    		        </td>
		    		        <td>
		    		          <%= order.order_status %>
		    		        </td>
		         	        <td>
		       	              <%= link_to "注文詳細", order_path(order), class: "glyphicon glyphicon-zoom-in btn btn-success" %>
		       	            </td>
		              </tr>
				          <% end %>
					</tbody>
				</table>
			</div>
			  <% else %>
		        <p>注文履歴がありません。</p>
		      <% end %>
		</div>
	</div>
</div>

app/views/customer/orders/log.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-9">
        <div class="title">
          <h2>注文情報確認</h2>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-xs-9">
        <table class="table table-hover table-inverse table-bordered">
          <thead>
            <tr class="info">
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>
          <tbody>
          <% @carts.each do |cart| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag(cart.item, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart.item.name %>
              </td>
              <td class="text-right">
                ¥<%= tax_price(cart.item.non_taxed_price).floor.to_s(:delimited) %>
              </td>
              <td class="text-right">
                  <%= cart.quantity %>
              </td>
              <td class="text-right">
                ¥<%= (cart.item.non_taxed_price * cart.quantity*1.1).floor.to_s(:delimited) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>

      <div class="col-xs-3">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">¥<%= @order.shipfee %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">¥<%= ((current_customer.total_price)*1.1).floor.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">¥<%= ((current_customer.total_price)*1.1+@order.shipfee).floor.to_s(:delimited) %></td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9">
      <h4><strong>支払方法</strong></h4>
         <td class="text-left">
            <%= @order.payment %>
         </td>
      <h4><strong>お届け先</strong></h4>
        <div><%= @order.zipcode %>
        <div><%= @order.address %></div>
        <div><%= @order.name %></div>
    </div>


    <div class ="col-xs-11">
      <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :zipcode %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :payment %>
        <%= f.hidden_field :total_price %>
        <%= f.hidden_field :shipfee %>
        <%= f.hidden_field :order_status, :value => "入金待ち" %>
        <%= f.submit "購入を確定する", class: "btn-lg btn-success col-xs-offset-5" %>
      <% end %>
    </div>
  </div>

app/views/customer/orders/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12">

         <div class="title">
            <h2>注文情報入力</h2>
         </div>
        
        <%= form_with url:log_orders_path, method: :get, local: true do | f | %>
           <h4><strong>支払方法</strong></h4>
              <p>
              <%= f.radio_button :payment_method, "クレジットカード", checked: true %>
              クレジットカード
              </p>
              <p>
              <%= f.radio_button :payment_method, "銀行振込" %>
              銀行振込
              </p>

          <h4><strong>お届け先</strong></h4>
               <p><%= f.radio_button :address_option, "address", checked: true  %>
                 ご自身の住所
                  <div><%= current_customer.zipcode %><%= current_customer.address %></div>
                  <div><%= current_customer.family_name %><%= current_customer.first_name %></div>

               </p>
               <p><%= f.radio_button :address_option, "addresses" %>
                 登録済住所から選択
                 <%= f.collection_select :addresses, current_customer.addresses, :id, :name, :prompt =>'---選択してください---' %>
               </p>
               <p><%= f.radio_button :address_option, "new_address" %>
                 新しいお届け先
                    <div class="field form-group col-xs-11">
                      <%= f.label :"郵便番号(ハイフンなし)", class: "col-sm-4 control-label" %>
                      <%= f.text_field :zipcode, class: "col-sm-3" %>
                    </div>
                    <div class="field form-group col-xs-11">
                      <%= f.label :"住所", class: "col-sm-4 control-label" %>
                      <%= f.text_field :address, class: "col-sm-8" %>
                    </div>
                    <div class="field form-group col-xs-11">
                      <%= f.label :"宛名", class: "col-sm-4 control-label" %>
                      <%= f.text_field :name, class: "col-sm-4" %>
                    </div>
                        <%= f.submit "確認画面に進む", class:"btn-lg btn-success col-xs-offset-5" %>
                    <% end %>
                  </div>
               </p>

         </div>
    </div>

app/views/customer/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="order-show col-xs-10 col-xs-offset-1">
			<div class="title">
	          <h2>注文履歴詳細</h2>
	        </div>

			<div class="row">
				<!-- 注文情報 -->
				<div class=" order-info col-xs-7">
					<h3>注文情報</h3>
					<div class="order-table">
						<table class="table">
							<tbody>
								<tr>
									<th class="active">注文日</th>
									<td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
								</tr>
								<tr>
									<th class="active">配送先</th>
									<td>
									  <%= @order.zipcode %><br>
									  <%= @order.address %><br>
				    		    	  <%= @order.name %>
									</td>
								</tr>
								<tr>
									<th class="active">支払方法</th>
									<td><%= @order.payment %></td>
								</tr>
								<tr>
									<th class="active">ステータス</th>
									<td> <%= @order.order_status %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<!-- 請求情報 -->
				<div class="col-xs-3">
					<h3>請求情報</h3>
					<div>
						<table class="table">
							<tbody>
								<tr>
									<th class="active">商品合計</th>
									<td class="text-right"> ¥<%= (@order.sub_price*1.10).floor.to_s(:delimited) %></td>
								</tr>
								<tr>
									<th class="active">配送料</th>
									<td class="text-right">¥<%= @order.shipfee %></td>
								</tr>
								<tr>
									<th class="active">ご請求額</th>
									<td class="text-right">¥<%= @order.total_price.floor.to_s(:delimited) %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!-- 注文内容 -->
			<div class="row">
				<div class="col-xs-8">
					<h3>注文内容</h3>
					<div>
						<table class="table">
							<thead>
								<tr>
									<th class="active">商品</th>
									<th class="active">単価（税込）</th>
									<th class="active">個数</th>
									<th class="active">小計</th>
								</tr>
							</thead>
							<tbody>
								<% @order.order_items.each do |order_item| %>
								<tr>
	    		          			<td><%= order_item.item.name %></td>
									<td class>¥<%= (order_item.purchase_price*1.10).floor.to_s(:delimited) %></td>
									<td class><%= order_item.quantity %></td>
									<td class>¥<%= (order_item.purchase_price*1.10*order_item.quantity).floor.to_s(:delimited) %></td>
								</tr>
								<% end %>

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/customer/orders/thanks.html.erb
<div class="container">
    <div class="row">
        <div class="box">
            <h2>ご購入ありがとうございました！</h2>
        </div>
    </div>
</div>