config/routes.rb
Rails.application.routes.draw do

# 管理者側
  #scope module: :admin do
    devise_for :admins
  #
  # , controllers: {
  #   sessions:      'admin/sessions',
  #   passwords:     'admin/passwords',
  #   registrations: 'admin/registrations'
  # }
  # root 'admin/sessions#top'
  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :order_items, only: [:update]
    get '/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end


# 顧客側
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  root 'customer/items#top'
  get '/about' => 'customer/items#about', as: 'about'

  scope module: :customer do
    scope 'customers' do

      resources :items, only: [:index, :show]
      resources :orders, only: [:new,  :create,  :index, :show] do
       collection do
          get 'log'
          get 'thanks'
        end
      end
      resource :customers, only: [:show, :edit, :update, :quit, :out] do
        collection do
          get 'quit'
          patch 'out'
       end
     end
     resources :carts, only: [:index, :create, :update, :destroy] do
       collection do
         delete 'all_destroy'
       end
     end
     resources :addresses, only: [:index, :create, :edit, :update, :destroy]
   end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          # sessionsコントローラーで使用する定義
  has_many :carts
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  has_many :addresses, dependent: :destroy
  has_many :orders

  def total_price
    sum = 0
    self.carts.each do |cart_item|
     sum += cart_item.quantity * cart_item.item.non_taxed_price
    end
    return sum
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  def quit
  end

  def out
  end
  
  private

  def customer_params
    params.require(:customer).permit(:family_name, :family_name_kana, :first_name, :first_name_kana, :phone_number, :zipcode, :address, :email, :is_deleted)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

before_action :authenticate_customer!

  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.address
      if @address.save
        redirect_to addresses_path
      else
        @addresses = current_customer.address
        render 'index'
      end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
      if @address.update(address_params)
        redirect_to addresses_path
      else
        render "edit"
      end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    @addresses = current_customer.address
      redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:zipcode, :address, :name)

  end
end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController
  def index
    @carts = current_customer.carts
    @total_price = 0
		@carts.each do |cart|
			@total_price += cart.item.non_taxed_price * cart.quantity
		end
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.customer_id = current_customer.id
    # @carts = current_customer.carts
    @already = current_customer.carts.find_by(item_id: @cart.item_id)
    if @already.present?
      new_quantity = @already.quantity + @cart.quantity
      @already.update_attribute(:quantity, new_quantity)
    else
      @cart.save
    end
    redirect_to carts_path
  end

  def update
    @cart = Cart.find(params[:id])
    if @cart.update(cart_params)
      redirect_to carts_path
    else render 'index'
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    if @cart.destroy
      redirect_to carts_path
    else render 'index'
    end
  end

  def all_destroy
    Cart.destroy_all
    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:item_id, :quantity)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  def quit
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    # ログアウトしてトップページに飛ぶ
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:family_name, :family_name_kana, :first_name, :first_name_kana, :phone_number, :zipcode, :address)
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  MAX_DISPLAY_RELATED_PRODUCTS = 4

  def top
    @genres = Genre.where(directed_graph: true)
    # @items =Item.limit(8).offset(4)
    @items = Item.where(on_sale: true)
  end

  def about
  end

  def index
    @genres = Genre.where(directed_graph: true)
    @items = Item.where(on_sale: true).page(params[:page]).per(4)

  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(directed_graph: true)
    @cart = Cart.new
  end

  private
  def items_params
    params.require(:item).permit(:explanation, :non_taxed_price, :image, :on_sale, :genre_id)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @order = Order.new
    @address = Address.where(customer: current_customer)
  end

  def log
    @carts = Cart.all
		@order = Order.new

	  if params[:address_option] == "address"
      #ご自身の住所
      @order.zipcode = current_customer.zipcode
      @order.address = current_customer.address
      @order.name = current_customer.family_name + current_customer.first_name

    elsif params[:address_option] == "addresses"
      if params[:addresses].blank?
        render :new
        return
      end
        #登録済住所から選択
        @order.zipcode = Address.find(params[:addresses]).zipcode
        @order.address = Address.find(params[:addresses]).address
        @order.name = Address.find(params[:addresses]).name
      else params[:address_option] == "new_address"
        @order.zipcode = params[:zipcode]
        @order.address = params[:address]
        @order.name = params[:name]
    end

    @order.payment = params[:payment_method]
    @order.shipfee = 800

  end

  def create
    @order = Order.new(order_params)
    @order.total_price = current_customer.total_price * 1.10 + @order.shipfee
    @order.customer_id = current_customer.id
    @order.save!
    # もし情報入力でnew_addressの場合Addressに保存
    if params[:address_option] == "new_address"
      current_customer.addresses.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @carts = current_customer.carts
    @carts.each do |cart|
    # OrderItem.create(purchase_price: cart.item.non_taxed_price, order_id: @order.id, item_id: cart.item.id, quantity: cart.quantity)
    @order_item = OrderItem.new
    @order_item.purchase_price = cart.item.non_taxed_price
    @order_item.order_id = @order.id
    @order_item.item_id  = cart.item.id
    @order_item.quantity = cart.quantity
    @order_item.save
    end

    # 注文完了後、カート商品を空にする
  # @carts.destroy_all
    if @order.save
      @carts = current_customer.carts
      @carts.destroy_all
      redirect_to thanks_orders_path
    else
      @order.customer_id = current_customer.id
      @customer = current_customer
      render :new
    end
  end

  def thanks
  end

  def index
      @orders = Order.all
      #Order.where(customer_id: current_customer.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_status = @order.order_status
  end

  private
    def address_params
      params.require(:order).permit(:zipcode, :address, :name)
    end

    def order_params
      params.require(:order).permit( :name, :zipcode, :address, :payment, :shipfee, :order_status)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def after_sign_in_path_for(resource)
   customers_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :email, :zipcode, :address, :phone_number ])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]

  # # GET /resource/sign_in
  # # def new
  # #   super
  # # end

  # # POST /resource/sign_in
  # # def create
  # #   super
  # # end

  # # DELETE /resource/sign_out
  # # def destroy
  # #   super
  # # end

 protected
 # 退会済のユーザーを弾く
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end

  def quit
  end

  def out
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="Title">
        <h2><%= @customer.family_name %><%= @customer.first_name %>さんの会員情報編集</h2>
      </div>
    </div>
  </div>
  <br>
  <%= form_with model:@customer, url:admin_customer_path, local:true do |f| %>
    <div class="row">
      <div class="col-xs-10">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th class="info col-xs-2">顧客ID</th>
              <td>
                <%= @customer.id %>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">
                <%= f.label :"氏名" %>
              </th>
              <td>
                <%= f.text_field :family_name, autofocus: true %>
                <%= f.text_field :first_name %>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">
                <%= f.label :"フリガナ" %>
              </th>
              <td>
                <%= f.text_field :family_name_kana %>
                <%= f.text_field :first_name_kana %>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">
                <%= f.label :"メールアドレス" %>
              </th>
              <td>
                <%= f.email_field :email, class: "col-xs-7 form-control-static email" %>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">
                <%= f.label :"郵便番号" %>
              </th>
              <td>
                <%= f.text_field :zipcode %>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">
                <%= f.label :"住所" %>
              </th>
              <td>
                <%= f.text_field :address, class: "col-xs-7 form-control-static address" %>
              </td>
            </tr>
            <tr>
            <th class="info col-xs-2">
              <%= f.label :"電話番号" %>
            </th>
            <td>
              <%= f.text_field :phone_number %>
            </td>
            </tr>
            <tr>
              <th class="info col-xs-2"></th>
              <td>
                有効
                <%= f.radio_button :is_deleted, :false %>
                退会済み
                <%= f.radio_button :is_deleted, :true %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="form-group col-xs-12">
      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="title">
    <h2>会員一覧</h2>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= customer.family_name %>
              <%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == true %>
              <p>退会済</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
      <div class="Title">
        <h2><%= @customer.family_name %><%= @customer.first_name %>さんの会員詳細</h2>
      </div>
      <br>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th class="info col-xs-2">顧客ID</th>
              <td><%= @customer.id %>
              <% if @customer.is_deleted == true %>
                退会済
              <% else %>
               有効会員
              <% end%>
              </td>
            </tr>
            <tr>
              <th class="info col-xs-2">氏名</th>
              <td><%= @customer.family_name %><%= @customer.first_name %></td>
            </tr>
          <tr>
          <th class="info col-xs-2">カナ</th>
            <td>
              <%= @customer.family_name_kana %>
              <%= @customer.first_name_kana %>
            </td>
          </tr>
          <tr>
            <th class="info col-xs-2">郵便番号</th>
            <td>
              <%= @customer.zipcode %>
            </td>
          </tr>
          <tr>
            <th class="info col-xs-2">住所</th>
            <td>
              <%= @customer.address %>
            </td>
          </tr>
          <tr>
            <th class="info col-xs-2">電話番号</th>
            <td>
              <%= @customer.phone_number %>
            </td>
          </tr>
          <tr>
            <th class="info col-xs-2">メールアドレス</th>
            <td>
              <%= @customer.email %>
            </td>
          </tr>
        </tbody>
        </table>
          <%= link_to '編集する', edit_admin_customer_path, class: "btn btn-primary" %>
          <%= link_to '注文内容一覧', admin_orders_path(@customer), class: "btn btn-primary" %>
      </div>
    </div>
  </div>