config/routes.rb
Rails.application.routes.draw do

# 管理者側
  #scope module: :admin do
    devise_for :admins
  #
  # , controllers: {
  #   sessions:      'admin/sessions',
  #   passwords:     'admin/passwords',
  #   registrations: 'admin/registrations'
  # }
  # root 'admin/sessions#top'
  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :order_items, only: [:update]
    get '/top' => 'items#top', as: 'top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end


# 顧客側
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  root 'customer/items#top'
  get '/about' => 'customer/items#about', as: 'about'

  scope module: :customer do
    scope 'customers' do

      resources :items, only: [:index, :show]
      resources :orders, only: [:new,  :create,  :index, :show] do
       collection do
          get 'log'
          get 'thanks'
        end
      end
      resource :customers, only: [:show, :edit, :update, :quit, :out] do
        collection do
          get 'quit'
          patch 'out'
       end
     end
     resources :carts, only: [:index, :create, :update, :destroy] do
       collection do
         delete 'all_destroy'
       end
     end
     resources :addresses, only: [:index, :create, :edit, :update, :destroy]
   end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order_items

  enum payment: {"クレジットカード": 0, "銀行振込": 1}
  enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

  def sub_price
    sum = 0
    self.order_items.each do |order_item|
      sum += order_item.purchase_price*order_item.quantity
    end
    return sum
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:id]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
       redirect_to admin_order_path(@order.id)
    else
       render 'show'
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @order = Order.new
    @address = Address.where(customer: current_customer)
  end

  def log
    @carts = Cart.all
		@order = Order.new

	  if params[:address_option] == "address"
      #ご自身の住所
      @order.zipcode = current_customer.zipcode
      @order.address = current_customer.address
      @order.name = current_customer.family_name + current_customer.first_name

    elsif params[:address_option] == "addresses"
      if params[:addresses].blank?
        render :new
        return
      end
        #登録済住所から選択
        @order.zipcode = Address.find(params[:addresses]).zipcode
        @order.address = Address.find(params[:addresses]).address
        @order.name = Address.find(params[:addresses]).name
      else params[:address_option] == "new_address"
        @order.zipcode = params[:zipcode]
        @order.address = params[:address]
        @order.name = params[:name]
    end

    @order.payment = params[:payment_method]
    @order.shipfee = 800

  end

  def create
    @order = Order.new(order_params)
    @order.total_price = current_customer.total_price * 1.10 + @order.shipfee
    @order.customer_id = current_customer.id
    @order.save!
    # もし情報入力でnew_addressの場合Addressに保存
    if params[:address_option] == "new_address"
      current_customer.addresses.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @carts = current_customer.carts
    @carts.each do |cart|
    # OrderItem.create(purchase_price: cart.item.non_taxed_price, order_id: @order.id, item_id: cart.item.id, quantity: cart.quantity)
    @order_item = OrderItem.new
    @order_item.purchase_price = cart.item.non_taxed_price
    @order_item.order_id = @order.id
    @order_item.item_id  = cart.item.id
    @order_item.quantity = cart.quantity
    @order_item.save
    end

    # 注文完了後、カート商品を空にする
  # @carts.destroy_all
    if @order.save
      @carts = current_customer.carts
      @carts.destroy_all
      redirect_to thanks_orders_path
    else
      @order.customer_id = current_customer.id
      @customer = current_customer
      render :new
    end
  end

  def thanks
  end

  def index
      @orders = Order.all
      #Order.where(customer_id: current_customer.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_status = @order.order_status
  end

  private
    def address_params
      params.require(:order).permit(:zipcode, :address, :name)
    end

    def order_params
      params.require(:order).permit( :name, :zipcode, :address, :payment, :shipfee, :order_status)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def log
  end

  def create
  end

  def thanks
  end

  def index
  end

  def show
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def tax_price(a)
    a * 1.1
  end

  # def sub_price(b)
  #   b.order_item.non_taxed_price * b.quantity
  # end
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="title">
        <h2>注文履歴一覧</h2>
      </div>
      <br>
      <%# if @orders.present? %>
      <div class="orders-table">
        <table class="table">
          <thead>
            <tr class="active">
              <th>購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>
              <th>注文ステータス</th>
            </tr>
          </thead>
          <tbody class="order">
            <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_order_path(order) do %>
                <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                <% end %>
              </td>
              <td>
                <%= order.name %>
              </td>
                <td>
                <% sum = 0 %>
                <% order.order_items.each do |item| %>
                  <% sum += item.quantity %>
                <% end %>
                <%= sum %>
                  <%#= order. %>
                </td>
              <td>
                <%= order.order_status %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%# else %>
		    <!--<p>注文履歴がありません。</p>-->
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="title">
      <h2>注文履歴詳細</h2>
    </div>
    <br>
    <div class="row">
      <div class="col-xs-12" >
		      <div class="field">
		        <div class="col-xs-4">購入者</div>
		        <div class="col-xs-8"><%= @order.name %></div>
          </div>
          <br>
          <div class="field">
	          <div class="col-xs-4">配送先</div>
	          <div class="col-xs-8">
	            <%= @order.zipcode %>
    					<%= @order.address %><br>
    				  <%= @order.name %>
            </div>
          </div>
          <br>
          <br>
          <div class="field">
	          <div class="col-xs-4">支払い方法</div>
            <div  class="col-xs-8">
              <%= @order.payment %>
            </div>
          </div>
          <br>
          <div class="field">
          <%= form_with( model: @order, url: admin_order_path, method: :patch, local: true ) do |f| %>
            <div class="col-xs-4">注文ステータス</div>
            <div class="col-xs-8">
              <%= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>
              <%= f.submit '更新', class: "btn btn-primary" %>
            </div>
            <br>
          <% end %>
      </div>
    </div>
  </div>
    <br>
    <br>
      <div class="row">
        <div class="col-xs-12">
          <div class=" order-info col-xs-7">
            <table class="table">
              <thead>
                <tr>
                  <th class="active">商品名</th>
                  <th class="active">単価（税込）</th>
                  <th class="active">数量</th>
                  <th class="active">小計</th>
                  <th class="active">制作ステータス</th>
                </tr>
              </thead>
              <tbody>
                <% @order_items.each do |order_item| %>
                  <tr>
                    <td><%= order_item.item.name %></td>
                    <td>¥<%= (order_item.purchase_price*1.1).floor.to_s(:delimited) %></td>
                    <td><%= order_item.quantity %></td>
                    <td>¥<%= (order_item.purchase_price*1.10*order_item.quantity).floor.to_s(:delimited) %></td>
                      <%= form_with( model: order_item, url: admin_order_item_path(order_item), local: true, method: :patch) do |f| %>
                        <td>
                          <%= f.select :making_status, OrderItem.making_statuses.keys, class: "making_status" %>
  			            	    <%= f.submit '更新' ,class: "btn btn-warning" %></td>
                      <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-xs-3">
        		<table  class="table">
        			<tr>
                <th class="active">商品合計</th>
        				<td class="text-right">¥<%= (@order.sub_price*1.1).floor.to_s(:delimited) %></td>
        			</tr>
        			<tr>
        				<th class="active">送料</th>
        				<td class="text-right">¥<%= @order.shipfee %></td>
        			</tr>
        			<tr>
        				<th class="active">請求金額合計</th>
        				<td class="text-right">¥<%= @order.total_price.floor.to_s(:delimited) %></td>
        			</tr>
        		</table>
    	    </div>
        </div>
      </div>
    </div>
</div>